name: ticket_wisata_donorojo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  intl: ^0.17.0
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.7
  flutter_svg: ^1.1.6
  flutter_image_slideshow: ^0.1.4
  image_picker: ^0.8.6
  file_picker: ^5.2.4
  provider: ^5.0.0
  firebase_auth: ^1.1.3
  google_fonts: ^3.0.1
  get_storage: ^2.0.3
  simple_animations: ^3.0.0-nullsafety.1
  page_transition: ^2.0.9
  firebase_storage: ^10.3.11
  crypto: ^3.0.1
  carousel_slider: ^4.2.1
  sqflite: any
  mysql1: ^0.19.0
  multi_image_picker2: ^5.0.2
  barcode_widget: ^2.0.3
  flutter_speed_dial: ^6.2.0
  flutter_barcode_scanner: ^2.0.0
  geolocator: ^9.0.2
  permission_handler: ^9.0.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo-pacitan.webp
    - assets/image/klayar.jpeg
    - assets/image/pangasan.jpeg
    - assets/image/srau.jpeg
    - assets/image/one.png
    - assets/image/image-travel.webp
    - assets/background/bg.jpg
    - assets/image/
