name: WisataKU
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  intl: ^0.18.1
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.7
  flutter_svg: ^2.0.6
  flutter_image_slideshow: ^0.1.4
  image_picker: ^0.8.6
  file_picker: ^5.2.4
  provider: ^6.0.5
  firebase_auth: ^4.6.1
  # google_fonts: ^3.0.1
  get_storage: ^2.0.3
  simple_animations: ^3.0.0-nullsafety.1
  page_transition: ^2.0.9
  firebase_storage: ^11.2.1
  crypto: ^3.0.1
  carousel_slider: ^4.2.1
  sqflite: any
  mysql1: ^0.20.0
  multi_image_picker2: ^5.0.2
  barcode_widget: ^2.0.3
  flutter_speed_dial: ^7.0.0
  flutter_barcode_scanner: ^2.0.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  google_maps_flutter: ^2.2.5
  google_fonts: ^4.0.4
  firebase_core_platform_interface: 4.8.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/logo-pacitan.webp
    - assets/image/klayar.jpeg
    - assets/image/pangasan.jpeg
    - assets/image/srau.jpeg
    - assets/image/one.png
    - assets/image/image-travel.webp
    - assets/background/bg.jpg
    - assets/image/
