// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvb-jGLoRyqgyydyM12KsNujXNZVzg15I',
    appId: '1:678433047441:web:97425989f43f67cb5d9030',
    messagingSenderId: '678433047441',
    projectId: 'ticket-wisata-donorojo',
    authDomain: 'ticket-wisata-donorojo.firebaseapp.com',
    storageBucket: 'ticket-wisata-donorojo.appspot.com',
    measurementId: 'G-SJRKH94C8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDopzsT_IOETGzFms0Bff5sWyI1z_5ZnSw',
    appId: '1:678433047441:android:7e7f89c8bb98e2d75d9030',
    messagingSenderId: '678433047441',
    projectId: 'ticket-wisata-donorojo',
    storageBucket: 'ticket-wisata-donorojo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnpxQsbquoMtsL4noYopy9FpzFexfMO8k',
    appId: '1:678433047441:ios:6fe5189506ec26bf5d9030',
    messagingSenderId: '678433047441',
    projectId: 'ticket-wisata-donorojo',
    storageBucket: 'ticket-wisata-donorojo.appspot.com',
    iosClientId: '678433047441-ake7fbtg74u51l3cgul5uv62gmddbfmh.apps.googleusercontent.com',
    iosBundleId: 'com.hadiwi.ticketWisataDonorojo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnpxQsbquoMtsL4noYopy9FpzFexfMO8k',
    appId: '1:678433047441:ios:6fe5189506ec26bf5d9030',
    messagingSenderId: '678433047441',
    projectId: 'ticket-wisata-donorojo',
    storageBucket: 'ticket-wisata-donorojo.appspot.com',
    iosClientId: '678433047441-ake7fbtg74u51l3cgul5uv62gmddbfmh.apps.googleusercontent.com',
    iosBundleId: 'com.hadiwi.ticketWisataDonorojo',
  );
}
